### ISSUE TITLE
On the useless repair packets

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#2]
DO: Fine, but
you miss the opposite case: how many repair packets are you sending that turn
out to be useless? It's a matter of measuring the usefulness of repair traffic.
It gives an extra degree of freedom as you may want to play at the congestion
control level or at the coding rate level. NK: Good point, that's the kind of
topic we need to gather in the document. There are several corner cases that
are very important. This point is about how you add coding inside congestion
control. With this claim, we want to be generic.

**Comment by mwelzl** [comment]
I think this document ought to remove the confusion between coding and congestion control that folks seem to have. So: "It gives an extra degree of freedom as you may want to play at the congestion control level or at the coding rate level." sounds like it's based on this confusion. And: "This point is about how you add coding inside congestion control." doesn't seem right either.

**Comment by NicoKos** [comment]
Indeed - the introduction of the coding and congestion channels could help. I may need to be reflected in the rest of the document.

**Comment by francoismichel** [comment]
Maybe we could emphasize on the fact that coding is a reliability mechanism and is distinct and separated from the loss detection and congestion control mechanisms. 

If all we care about is bandwidth in a general unicast scenario, sending a-priori repair packets should not help more than Selective-Repeat ARQ. In the best case, it should perform as well as a SR-ARQ if the packet is lost (without additional gain), and will simply waste bandwidth compared to SR-ARQ if the packet is not lost.

I can identify one case where doing FEC can help for bandwidth: when the buffer are full or very limited and cannot be in-order delivered to the application because of head-of-line blocking. Sending FEC could help to unblock the peer's receive buffer sooner. But this has nothing to do with congestion control.

**Comment by NicoKos** [comment]
I think this kind of discussion should be in the document.

**Comment by mwelzl** [comment]
I agree with @francoismichel 's idea of unblocking the receiver. Also, in the other issue, he mentioned the big disadvantage (delay) coming from tail losses. These things should now be added to the document - now it's structured such that it could be added better, in the right place.

Other thoughts that were brought up in discussions, and should go into the doc - both are about the FEC-below-transport case:

1) ECN:

From @francoismichel :
> if the coding is performed in a layer between IP and congestion-controlled transport protocol, the coding layer must include a mechanism to detect network congestion and when congestion seems to be present, it must relay the information to the above layer using mechanisms such as ECN

There is more detail about possibilities to use ECN for FEC-below-transport in Emmanuel's presentation:
https://datatracker.ietf.org/meeting/100/materials/slides-100-nwcrg-07-lochin-on-the-joint-use-of-tcp-and-network-coding-00  (slide 4)


2) special environments:

and we had this discussion in a PR related to FEC-below-transport:
@francoismichel  wrote:
> But then what about the solutions that protect TCP connections running on a link (e.g. satellite link) where losses should not be due to congestion ? These are solutions that improve drastically performances, are easy to deploy and are not harmful in a congestion point of view. What is your opinion about this ? I am not sure myself.

and I answered:

> Interesting to discuss those things! These are cases where the environment is known so well that it is clear that hiding these losses won't create a problem. So we can say: don't generally hide losses UNLESS you know for sure that they are not due to congestion. This also fits well in an implementation discussion structured around the 3 layering possibilities (above, inside, below).


.... and about the FEC-above-transport case slide 2 reminds me that this is obviously useless if the transport repairs all losses, as with TCP!  This is worth mentioning in the FEC-above-transport case - we could mention that unreliable congestion-controlled transports (e.g. RMCAT cc's, or DCCP) are better to consider here than fully reliable ones such as TCP.

**Comment by francoismichel** [comment]
I am unsure where this issue is going and what we can integrate in the draft then. I would say that identifying useless repair packets is the work of the reliability mechanism (there is a clear similarity with spurious retransmissions detection) and in my opinion has nothing to do with congestion control, so what can we integrate in the draft ?

**Comment by NicoKos** [comment]
I think this discussion is covered in PR #29
