### ISSUE TITLE
MJM comments on the research aspects of the draft

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#58]
- This is an IRTF document how is this relating to current research and where?
- CC and NC are essentially two competing control loops - there is a lot of heritage on that topic (outside networking too) - what can NC/CC learn from that - any research questions?
- My experience with NC is that the most gains are in low loss networks (far from network capacity) - where in fact CC protocols over react- is there research on appropriate metrics?
- Most of the gain seems to be in last-mile/access networks - any other research?
-> All of this to say that the draft should be clearer on the type of research that is needed again when the performance is impacted 2 conflicting control loops.

**Comment by mwelzl** [comment]
I think the draft touches upon quite a number of research ideas / possibilities, but they're "hidden" in the structure perhaps... so I believe this is a matter of making them explicit, let them stand out - perhaps a section towards the end that summarizes pulls them together and summarizes?

**Comment by patibulon** [comment]
It would be good. Thanks.

mjm

Marie-José Montpetit, Ph.D.
marie@mjmontpetit.com



From: mwelzl <notifications@github.com> <notifications@github.com>
Reply: irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport
<reply@reply.github.com>
<reply@reply.github.com>
Date: March 9, 2021 at 3:19:41 AM
To: irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport
<draft-irtf-nwcrg-coding-and-congestion-in-transport@noreply.github.com>
<draft-irtf-nwcrg-coding-and-congestion-in-transport@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re:
[irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport] MJM
comments on the research aspects of the draft (#58)

I think the draft touches upon quite a number of research ideas /
possibilities, but they're "hidden" in the structure perhaps... so I
believe this is a matter of making them explicit, let them stand out -
perhaps a section towards the end that summarizes pulls them together and
summarizes?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/issues/58#issuecomment-793531227>,
or unsubscribe

**Comment by NicoKos** [comment]
I think this is covered by the research questions in the dedicated section - see PR #63
