### ISSUE TITLE
Section 4 Figure 6 

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#70]
It is a bit complicated for me to understand correctly the details of Figure 6 :  

```
    | source  | sending                    ^ source
    | packets | rate                       | packets
    v         v                            |
   +------------+                      +------------+
   | Transport  |                      | Transport  |
   |            |                      |            |
   | +---+ +--+ |             signaling| +---+ +--+ |
   | |FEC| |CC| |              repaired| |FEC| |CC| |
   | +---+ +--+ |source         symbols| +---+ +--+ |
   |            |and/or             <==|            |
   |            |repair         network|            |
   |            |packets    information|            |
   +------------+ ==>               <==+------------+

       SENDER                              RECEIVER

                       Figure 6: FEC in the transport
```

In my opinion, the app does not sublit packets nor a sending rate to the transport layer, so the two arrows above the sender seem a bit weird for me. The app generally submits data, sometimes messages and maybe a minimal transmission rate but it is the transport layer that packetizes the data and sends packets.

I guess that the arriws between the sender and the receiver are the wire or the layers below transport. Thus I would replace "source and/or repair packets" by "packets containing source and/or repair symbols"

Did I misunderstand the Figure ?

**Comment by mwelzl** [comment]
I agree; I think the "sending rate" arrow can be removed (I'd say that the rate is at least implicit, in how fast the application gives data to the stack, but this just complicates matters - no need for this arrow anyway). I also think that "source packets" could just be "data" (next to the arrows on the top).

This applies to figure 5 too ("source packets" can be replaced with "data" next to these arrows), and in figure 3, in the top left corner, the arrow could also be called "data" instead of "source packets".

**Comment by NicoKos** [comment]
There have been some changes due to the issue #65  - I proposed a commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/288a4334b1011b69096ffbbdb0da5a387a847c56 and commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/8b49d61c8331267af73e13c32cf79311bd6aabba in pr #72 to clarify the unnecessary arrow.
